global:
  scrape_interval:     15s 
  evaluation_interval: 15s 
scrape_configs:
- job_name: "node_exporter"
  consul_sd_configs:
    - server: "consul-2:8500"
      datacenter: "dc1"
      services: [node_exporter]
  relabel_configs:
    - source_labels: [__address__]
      target_label: instance